image: gitpod/workspace-rust

tasks:
    - name: run front-end
      openMode: split-left
      command: |
          rustup target add wasm32-unknown-unknown
          trunk serve --port 3000

ports:
    - name: front-end
      port: 3000
      onOpen: open-browser
      visibility: public

vscode:
  extensions:
    - rust-lang.rust-analyzer@0.3.1348

